### ISSUE TITLE
[Bungee/Waterfall] Incompatible with docker-compose?

### ISSUE THREAD

**Issue by spectrapulse** [Pandentia/Dockerfiles#2]
When trying to use Waterfall or Bungee with docker-compose, trying to mount volumes to the host will cause permission errors and refuse to create the files on the host.
```yaml
# docker-compose.yml
version: "3"
services:
    proxy:
        image: pandentia/waterfall:latest
        restart: unless-stopped
        volumes:
            - ./proxy:/server/work
        ports: 
            - "25565:25575"
```

Waterfall Exception: 
```
proxy_1    | Could not register logger!
proxy_1    | java.nio.file.AccessDeniedException: proxy.log.0.lck
proxy_1    |    at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
proxy_1    |    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
proxy_1    |    at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
proxy_1    |    at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(Unknown Source)
proxy_1    |    at java.base/java.nio.channels.FileChannel.open(Unknown Source)
proxy_1    |    at java.base/java.nio.channels.FileChannel.open(Unknown Source)
proxy_1    |    at java.logging/java.util.logging.FileHandler.openFiles(Unknown Source)
proxy_1    |    at java.logging/java.util.logging.FileHandler.<init>(Unknown Source)
proxy_1    |    at java.logging/java.util.logging.FileHandler.<init>(Unknown Source)
proxy_1    |    at net.md_5.bungee.log.BungeeLogger.<init>(BungeeLogger.java:28)
proxy_1    |    at net.md_5.bungee.BungeeCord.<init>(BungeeCord.java:218)
proxy_1    |    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:59)
proxy_1    |    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```
